version: '3.8'
services:

  worker:
    build:
      dockerfile: ./Kapitalist.Worker/Dockerfile.dev
    environment:
      - DOTNET_ENVIRONMENT=Development
      - "RpcClients__RatesServiceClient__Host=rates-api" #kapitalist.pro
      - "PlatformSettings__JobFrequencySeconds=60"
    volumes:
      - ./Kapitalist.Worker/logs:/logs

  rates-api:
    build:
      dockerfile: ./Kapitalist.RatesApi/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__AppDbContext=Server=rates-db;Database=rates;Port=5432;User Id=postgres;Password=postgres_password;"
    volumes:
      - ./Kapitalist.Worker/logs:/logs
  
  rates-db:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=rates
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always    
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=postgres_password
    ports:
      - 9010:80
    depends_on: 
      - rates-db