version: '3.8'
services:

  worker:
    build:
      context: .
      dockerfile: ./Kapitalist.Worker/Dockerfile
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=docker
      - "RpcClients__RatesServiceClient__Host=rates-api"
      - "RpcClients__RatesServiceClient__Port=5011"

  rates-api:
    build:
      context: .
      dockerfile: ./Kapitalist.RatesApi/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=docker

  rates-db:
    image: postgres
    restart: always