version: '3.8'
services:

  worker:
    build:
      context: .
      dockerfile: ./Kapitalist.Worker/Dockerfile
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=docker
      - "RpcClients__RatesServiceClient__Host=rates-api"
    depends_on: 
      - rates-api

  rates-api:
    build:
      context: .
      dockerfile: ./Kapitalist.RatesApi/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - 5010:5010
      - 5011:5011
    depends_on: 
      - rates-db

  rates-db:
    image: postgres
    restart: always