version: '3.8'
services:

  worker:
    build:
      context: .
      dockerfile: ./Kapitalist.Worker/Dockerfile
    restart: always

  rates-api:
    build:
      context: .
      dockerfile: ./Kapitalist.RatesApi/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=docker

  rates-db:
    image: postgres
    restart: always