// <auto-generated />
using System;
using Kapitalist.RatesApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Kapitalist.RatesApi.Migrations
{
    [DbContext(typeof(RatesDataContext))]
    [Migration("20210503150837_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Kapitalist.RatesApi.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("RateAsk")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RateBid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RatesSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("RatesSnapshotId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Kapitalist.RatesApi.Models.RatesSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RateType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("RatesSnapshots");
                });

            modelBuilder.Entity("Kapitalist.RatesApi.Models.Rate", b =>
                {
                    b.HasOne("Kapitalist.RatesApi.Models.RatesSnapshot", null)
                        .WithMany("CurrencyValues")
                        .HasForeignKey("RatesSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kapitalist.RatesApi.Models.RatesSnapshot", b =>
                {
                    b.Navigation("CurrencyValues");
                });
#pragma warning restore 612, 618
        }
    }
}
